stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  image: node:16.13.0
  stage: build
  only:
    - main
  script:
    - version_number=$(date +"%Y.%m.%d.%H%M-$CI_BUILD_REF_NAME")
    - echo "REACT_APP_VERSION='$version_number'" > .env
    - npm i
    - npm run build
  artifacts:
      when: on_success
      name: portfolio-build
      paths:
        - build
      expire_in: 1 hour
  
deploy: 
  image: ubuntu
  stage: deploy
  only:
    - main
  variables:
    SERVER_NAME: "EOD-WEB-01"
    SERVICE_ACCOUNT: "deploy"
  script:
    - apt update
    - apt install openssh-client -y
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$DEPLOY_SSH_PRIVATE_KEY" | tr -d '\r')
    - ssh-keyscan $SERVER_NAME >> ~/.ssh/known_hosts
    - scp -r ./build/* $SERVICE_ACCOUNT@$SERVER_NAME:/usr/share/nginx/portfolio/